[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps = 
	lovyan03/LovyanGFX@^1.2.19
	marian-craciunescu/ESP32Ping@^1.7
build_flags = 
	-D USER_SETUP_LOADED=1
	-D ST7789_DRIVER=1
	-D LGFX_USE_V1=1
	-D TFT_WIDTH=172
	-D TFT_HEIGHT=320
	-D TFT_RGB_ORDER=TFT_BGR
	-D TFT_INVERSION_ON=1
	-D SCREEN_ROTATION=1
